const mongoose = require('mongoose');
const Video = require('../models/Video');
require('dotenv').config();

// Best YouTube videos for different topics - Curated high-quality educational content
const sampleVideos = [
  // JavaScript Fundamentals - Best videos from top channels
  {
    title: 'JavaScript Crash Course for Beginners',
    description: 'Complete JavaScript tutorial by Traversy Media - variables, functions, arrays, objects, DOM manipulation',
    videoUrl: 'https://www.youtube.com/watch?v=hdI2bqOjy3c',
    videoId: 'hdI2bqOjy3c',
    thumbnailUrl: 'https://img.youtube.com/vi/hdI2bqOjy3c/maxresdefault.jpg',
    duration: 3600,
    topicId: 'js-fundamentals',
    subject: 'JavaScript',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'JavaScript Full Course for Beginners',
    description: 'Comprehensive JavaScript course by freeCodeCamp - 8 hours of content covering all fundamentals',
    videoUrl: 'https://www.youtube.com/watch?v=jS4aFq5-91M',
    videoId: 'jS4aFq5-91M',
    thumbnailUrl: 'https://img.youtube.com/vi/jS4aFq5-91M/maxresdefault.jpg',
    duration: 28800,
    topicId: 'js-fundamentals',
    subject: 'JavaScript',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 2,
  },
  {
    title: 'JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour',
    description: 'Quick and comprehensive JavaScript tutorial by Programming with Mosh',
    videoUrl: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
    videoId: 'W6NZfCO5SIk',
    thumbnailUrl: 'https://img.youtube.com/vi/W6NZfCO5SIk/maxresdefault.jpg',
    duration: 3600,
    topicId: 'js-fundamentals',
    subject: 'JavaScript',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 3,
  },
  {
    title: 'ES6 JavaScript Tutorial',
    description: 'Modern JavaScript features by Traversy Media - arrow functions, destructuring, spread operator, promises, async/await',
    videoUrl: 'https://www.youtube.com/watch?v=NCwa_xi0Uuc',
    videoId: 'NCwa_xi0Uuc',
    thumbnailUrl: 'https://img.youtube.com/vi/NCwa_xi0Uuc/maxresdefault.jpg',
    duration: 2400,
    topicId: 'js-es6',
    subject: 'JavaScript',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'JavaScript ES6 Tutorial',
    description: 'Complete ES6+ features tutorial by Net Ninja',
    videoUrl: 'https://www.youtube.com/watch?v=1mgLWu9ijvQ',
    videoId: '1mgLWu9ijvQ',
    thumbnailUrl: 'https://img.youtube.com/vi/1mgLWu9ijvQ/maxresdefault.jpg',
    duration: 3600,
    topicId: 'js-es6',
    subject: 'JavaScript',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 2,
  },
  {
    title: 'JavaScript Closures Explained',
    description: 'Deep dive into closures, scope chain, and lexical environment by Akshay Saini',
    videoUrl: 'https://www.youtube.com/watch?v=qikxEIxsXco',
    videoId: 'qikxEIxsXco',
    thumbnailUrl: 'https://img.youtube.com/vi/qikxEIxsXco/maxresdefault.jpg',
    duration: 1800,
    topicId: 'js-closures',
    subject: 'JavaScript',
    difficulty: 'Advanced',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'JavaScript Promises and Async/Await',
    description: 'Master asynchronous JavaScript with promises and async/await by Traversy Media',
    videoUrl: 'https://www.youtube.com/watch?v=PoRJizFExM4',
    videoId: 'PoRJizFExM4',
    thumbnailUrl: 'https://img.youtube.com/vi/PoRJizFExM4/maxresdefault.jpg',
    duration: 2400,
    topicId: 'js-async',
    subject: 'JavaScript',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  // React Basics - Best React tutorials
  {
    title: 'React Tutorial for Beginners',
    description: 'Complete React course by freeCodeCamp - components, props, state, hooks, routing',
    videoUrl: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
    videoId: 'bMknfKXIFA8',
    thumbnailUrl: 'https://img.youtube.com/vi/bMknfKXIFA8/maxresdefault.jpg',
    duration: 18000,
    topicId: 'react-basics',
    subject: 'React',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'React Crash Course 2021',
    description: 'Modern React tutorial by Traversy Media - hooks, context API, and best practices',
    videoUrl: 'https://www.youtube.com/watch?v=w7ejDZ8SWv8',
    videoId: 'w7ejDZ8SWv8',
    thumbnailUrl: 'https://img.youtube.com/vi/w7ejDZ8SWv8/maxresdefault.jpg',
    duration: 4200,
    topicId: 'react-basics',
    subject: 'React',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 2,
  },
  {
    title: 'React Hooks Complete Guide',
    description: 'Master all React hooks - useState, useEffect, useContext, useReducer, custom hooks',
    videoUrl: 'https://www.youtube.com/watch?v=TNhaISOUy6Q',
    videoId: 'TNhaISOUy6Q',
    thumbnailUrl: 'https://img.youtube.com/vi/TNhaISOUy6Q/maxresdefault.jpg',
    duration: 3000,
    topicId: 'react-hooks',
    subject: 'React',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'React Router Tutorial',
    description: 'Complete guide to React Router by Net Ninja - navigation, routes, protected routes',
    videoUrl: 'https://www.youtube.com/watch?v=Law7wfdg_ls',
    videoId: 'Law7wfdg_ls',
    thumbnailUrl: 'https://img.youtube.com/vi/Law7wfdg_ls/maxresdefault.jpg',
    duration: 3600,
    topicId: 'react-routing',
    subject: 'React',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  // Databases - Best database tutorials
  {
    title: 'SQL Tutorial for Beginners',
    description: 'Complete SQL course by freeCodeCamp - queries, joins, subqueries, and database design',
    videoUrl: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
    videoId: 'HXV3zeQKqGY',
    thumbnailUrl: 'https://img.youtube.com/vi/HXV3zeQKqGY/maxresdefault.jpg',
    duration: 16200,
    topicId: 'sql-basics',
    subject: 'Databases',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'SQL Full Course',
    description: 'Comprehensive SQL tutorial by Programming with Mosh',
    videoUrl: 'https://www.youtube.com/watch?v=7S_tz1z_5bA',
    videoId: '7S_tz1z_5bA',
    thumbnailUrl: 'https://img.youtube.com/vi/7S_tz1z_5bA/maxresdefault.jpg',
    duration: 14400,
    topicId: 'sql-basics',
    subject: 'Databases',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 2,
  },
  {
    title: 'MongoDB Complete Course',
    description: 'MongoDB tutorial by freeCodeCamp - NoSQL database, CRUD operations, aggregation',
    videoUrl: 'https://www.youtube.com/watch?v=ofme2o29ngU',
    videoId: 'ofme2o29ngU',
    thumbnailUrl: 'https://img.youtube.com/vi/ofme2o29ngU/maxresdefault.jpg',
    duration: 21600,
    topicId: 'mongodb-basics',
    subject: 'Databases',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'MongoDB Crash Course',
    description: 'Quick MongoDB tutorial by Traversy Media - setup, queries, and Mongoose',
    videoUrl: 'https://www.youtube.com/watch?v=-56x56UppqQ',
    videoId: '-56x56UppqQ',
    thumbnailUrl: 'https://img.youtube.com/vi/-56x56UppqQ/maxresdefault.jpg',
    duration: 3600,
    topicId: 'mongodb-basics',
    subject: 'Databases',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 2,
  },
  // Node.js - Best backend tutorials
  {
    title: 'Node.js Tutorial for Beginners',
    description: 'Complete Node.js course by freeCodeCamp - modules, file system, HTTP, streams',
    videoUrl: 'https://www.youtube.com/watch?v=TlB_eWDSMt4',
    videoId: 'TlB_eWDSMt4',
    thumbnailUrl: 'https://img.youtube.com/vi/TlB_eWDSMt4/maxresdefault.jpg',
    duration: 19800,
    topicId: 'nodejs-basics',
    subject: 'Node.js',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'Node.js Crash Course',
    description: 'Quick Node.js tutorial by Traversy Media - building REST APIs and web servers',
    videoUrl: 'https://www.youtube.com/watch?v=fBNz5xF-Kx4',
    videoId: 'fBNz5xF-Kx4',
    thumbnailUrl: 'https://img.youtube.com/vi/fBNz5xF-Kx4/maxresdefault.jpg',
    duration: 3600,
    topicId: 'nodejs-basics',
    subject: 'Node.js',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 2,
  },
  {
    title: 'Express.js Crash Course',
    description: 'Build RESTful APIs with Express.js by Traversy Media - routes, middleware, error handling',
    videoUrl: 'https://www.youtube.com/watch?v=L72fhGm1tfE',
    videoId: 'L72fhGm1tfE',
    thumbnailUrl: 'https://img.youtube.com/vi/L72fhGm1tfE/maxresdefault.jpg',
    duration: 2400,
    topicId: 'express-basics',
    subject: 'Node.js',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'Express.js Full Course',
    description: 'Complete Express.js tutorial by freeCodeCamp - middleware, routing, authentication',
    videoUrl: 'https://www.youtube.com/watch?v=SccSCuHhOw0',
    videoId: 'SccSCuHhOw0',
    thumbnailUrl: 'https://img.youtube.com/vi/SccSCuHhOw0/maxresdefault.jpg',
    duration: 10800,
    topicId: 'express-basics',
    subject: 'Node.js',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 2,
  },
  // Python - Best Python tutorials
  {
    title: 'Python for Beginners',
    description: 'Complete Python course by freeCodeCamp - syntax, data types, functions, OOP',
    videoUrl: 'https://www.youtube.com/watch?v=eWRfhZUzrAc',
    videoId: 'eWRfhZUzrAc',
    thumbnailUrl: 'https://img.youtube.com/vi/eWRfhZUzrAc/maxresdefault.jpg',
    duration: 25200,
    topicId: 'python-basics',
    subject: 'Python',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'Python Tutorial for Beginners',
    description: 'Python crash course by Programming with Mosh - quick and comprehensive',
    videoUrl: 'https://www.youtube.com/watch?v=kqtD5dpn9C8',
    videoId: 'kqtD5dpn9C8',
    thumbnailUrl: 'https://img.youtube.com/vi/kqtD5dpn9C8/maxresdefault.jpg',
    duration: 3600,
    topicId: 'python-basics',
    subject: 'Python',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 2,
  },
  {
    title: 'Python OOP Tutorial',
    description: 'Object-Oriented Programming in Python by freeCodeCamp - classes, inheritance, polymorphism',
    videoUrl: 'https://www.youtube.com/watch?v=Ej_02ICOIgs',
    videoId: 'Ej_02ICOIgs',
    thumbnailUrl: 'https://img.youtube.com/vi/Ej_02ICOIgs/maxresdefault.jpg',
    duration: 5400,
    topicId: 'python-oop',
    subject: 'Python',
    difficulty: 'Intermediate',
    provider: 'YouTube',
    order: 1,
  },
  {
    title: 'Python Full Course',
    description: 'Complete Python programming course by freeCodeCamp - from basics to advanced',
    videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    videoId: 'rfscVS0vtbw',
    thumbnailUrl: 'https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg',
    duration: 25200,
    topicId: 'python-basics',
    subject: 'Python',
    difficulty: 'Beginner',
    provider: 'YouTube',
    order: 3,
  },
];

const seedVideos = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/learning-path-generator');
    console.log('Connected to MongoDB');

    // Clear existing videos (optional - remove if you want to keep existing)
    // await Video.deleteMany({});

    // Insert videos
    for (const videoData of sampleVideos) {
      await Video.findOneAndUpdate(
        { videoId: videoData.videoId },
        videoData,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }

    console.log(`✅ Seeded ${sampleVideos.length} videos`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding videos:', error);
    process.exit(1);
  }
};

seedVideos();

